### ISSUE TITLE
Failing to compile on Rust 1.80, time-rs issue

### ISSUE THREAD

**Issue by wasabii** [indygreg/apple-platform-rs#150]
Same issue as tracked here: https://github.com/time-rs/time/issues/696

I suspect just bumping the 'time' version in Cargo.lock would resolve it?

**Comment by wasabii** [comment]
Also looks like it's failing in your own builds:

https://github.com/indygreg/apple-platform-rs/actions/runs/10354643393/job/28660389869#step:6:499

**Comment by indygreg** [comment]
I pushed a pile of crate updates a few hours ago and believe this issue has been resolved.

**Comment by theoparis** [comment]
I just noticed `cargo build` on the msrv of rust 1.78 fails with an error for the dependency of rasn, snafu:
```
error[E0658]: use of unstable library feature 'error_in_core'
   --> /home/theo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snafu-0.8.5/src/lib.rs:343:9
    |
343 | pub use core::error;
    |         ^^^^^^^^^^^
    |
    = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information

error[E0658]: use of unstable library feature 'error_in_core'
   --> /home/theo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snafu-0.8.5/src/lib.rs:347:9
    |
347 | pub use core::error::Error;
    |         ^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information

```

This seems to be have been stabilized in Rust 1.81.0.
